/* The following code was generated by JFlex 1.6.1 */


package Analizadores;
import java_cup.runtime.*;
import static Analizadores.IDE.TABLA_DE_ERRORES_SINTACTICOS;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Analizador_Lexico.jflex</tt>
 */
public class Analizador_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENT_SIMPLE = 2;
  public static final int COMENT_MULTI = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 55,  4, 10, 11,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    55, 45,  3,  8,  0, 40, 43,  0, 34, 51, 12, 36, 54, 37,  2, 38, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 47, 48, 42, 35, 41, 46, 
     0, 27, 26, 30, 22, 16, 15,  6, 21, 14,  6, 29, 17,  6, 25, 23, 
    33,  6, 24, 19, 31, 32,  6, 20,  6,  6,  6, 52,  5, 53, 39,  7, 
     0, 27, 26, 30, 22, 16, 15,  6, 21, 14,  6, 29, 17,  6, 25, 23, 
    33,  6, 24, 19, 31, 32,  6, 20,  6,  6,  6, 49, 44, 50,  0,  0, 
     0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\1\1\3\1\4\1\1\1\5"+
    "\1\1\3\4\1\1\10\4\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\1\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\2\0\1\32\2\0\2\33\1\0\1\34\1\35"+
    "\1\34\1\35\3\4\1\0\3\4\1\36\4\4\1\37"+
    "\2\4\1\40\1\41\1\42\1\43\1\44\1\45\1\32"+
    "\2\33\2\0\1\46\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\5\4\1\0\2\4\1\0\1\4\2\0\1\33"+
    "\1\47\1\33\3\0\1\4\2\50\1\0\1\4\1\0"+
    "\2\4\1\51\2\4\2\52\1\53\1\0\1\4\1\47"+
    "\3\0\1\47\2\54\1\0\1\4\2\55\1\4\2\56"+
    "\1\0\1\4\2\57\1\47\2\60\1\4\1\0\1\4"+
    "\1\61\1\0\1\4\2\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\160\0\u0150"+
    "\0\u0188\0\160\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\160"+
    "\0\u0498\0\160\0\160\0\160\0\160\0\u04d0\0\u0508\0\u0540"+
    "\0\160\0\160\0\u0578\0\160\0\160\0\160\0\160\0\160"+
    "\0\160\0\160\0\160\0\160\0\u05b0\0\u0118\0\160\0\u05e8"+
    "\0\u0620\0\160\0\u0658\0\u0690\0\160\0\160\0\u0150\0\u0150"+
    "\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0150"+
    "\0\u0850\0\u0888\0\u08c0\0\u08f8\0\160\0\u0930\0\u0968\0\160"+
    "\0\160\0\160\0\160\0\160\0\u05b0\0\u0118\0\u09a0\0\u09d8"+
    "\0\u09a0\0\u0a10\0\u0150\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28"+
    "\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8"+
    "\0\u0d20\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0620\0\u0e70"+
    "\0\u0e38\0\u0ea8\0\u0ee0\0\u0f18\0\160\0\u0150\0\u0f50\0\u0f88"+
    "\0\u0fc0\0\u0ff8\0\u1030\0\u0150\0\u1068\0\u10a0\0\160\0\u0150"+
    "\0\u0150\0\u10d8\0\u1110\0\160\0\u1148\0\u1180\0\u11b8\0\u1180"+
    "\0\160\0\u0150\0\u11f0\0\u1228\0\160\0\u0150\0\u1260\0\160"+
    "\0\u0150\0\u1298\0\u12d0\0\160\0\u0150\0\u11b8\0\160\0\u0150"+
    "\0\u1308\0\u1340\0\u1378\0\u0150\0\u13b0\0\u13e8\0\160\0\u0150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\10\1\3"+
    "\1\11\1\7\1\0\1\7\1\12\1\13\1\14\1\15"+
    "\1\16\1\10\1\17\1\20\1\21\1\10\1\22\2\10"+
    "\1\23\1\24\1\10\1\3\1\10\1\25\1\26\1\10"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\7\4\3"+
    "\1\7\3\3\1\11\1\7\1\0\1\7\53\3\1\7"+
    "\71\0\1\4\1\55\73\0\1\10\7\0\4\10\1\0"+
    "\11\10\1\0\5\10\26\0\3\56\1\57\1\0\1\60"+
    "\62\56\1\0\2\10\3\0\2\10\6\0\4\10\1\0"+
    "\11\10\1\0\5\10\12\0\1\10\13\0\4\61\1\62"+
    "\4\61\1\63\2\0\1\64\53\61\17\0\1\65\11\0"+
    "\1\66\37\0\2\10\3\0\2\10\6\0\1\10\1\67"+
    "\2\10\1\0\6\10\1\70\2\10\1\0\5\10\12\0"+
    "\1\10\14\0\2\10\3\0\2\10\6\0\4\10\1\0"+
    "\4\10\1\71\3\10\1\72\1\0\5\10\12\0\1\10"+
    "\14\0\2\10\3\0\2\10\6\0\3\10\1\73\1\0"+
    "\11\10\1\0\5\10\12\0\1\10\37\0\1\74\44\0"+
    "\2\10\3\0\2\10\6\0\4\10\1\0\1\10\1\75"+
    "\7\10\1\0\5\10\12\0\1\10\14\0\2\10\3\0"+
    "\2\10\6\0\4\10\1\0\2\10\1\76\6\10\1\0"+
    "\5\10\12\0\1\10\14\0\2\10\3\0\2\10\6\0"+
    "\2\10\1\77\1\10\1\0\4\10\1\100\4\10\1\0"+
    "\5\10\12\0\1\10\14\0\2\10\3\0\2\10\6\0"+
    "\4\10\1\0\11\10\1\0\3\10\1\101\1\10\12\0"+
    "\1\10\14\0\2\10\3\0\2\10\6\0\4\10\1\0"+
    "\5\10\1\102\3\10\1\0\5\10\12\0\1\10\14\0"+
    "\2\10\3\0\2\10\6\0\4\10\1\0\4\10\1\103"+
    "\3\10\1\104\1\0\5\10\1\105\11\0\1\10\14\0"+
    "\2\10\3\0\2\10\6\0\4\10\1\0\5\10\1\106"+
    "\3\10\1\0\5\10\12\0\1\10\14\0\2\10\3\0"+
    "\2\10\6\0\4\10\1\0\5\10\1\107\3\10\1\0"+
    "\5\10\12\0\1\10\56\0\1\110\74\0\1\111\62\0"+
    "\1\112\67\0\1\113\67\0\1\114\25\0\1\115\66\0"+
    "\3\56\1\116\1\0\1\60\62\56\4\61\1\62\4\61"+
    "\1\63\2\0\54\61\4\0\1\62\63\0\4\64\1\117"+
    "\4\64\1\120\2\121\1\122\53\64\1\0\2\10\3\0"+
    "\2\10\6\0\4\10\1\0\5\10\1\123\3\10\1\0"+
    "\5\10\12\0\1\10\14\0\2\10\3\0\2\10\6\0"+
    "\3\10\1\124\1\0\11\10\1\0\5\10\12\0\1\10"+
    "\14\0\2\10\3\0\2\10\6\0\4\10\1\125\1\126"+
    "\10\10\1\0\5\10\12\0\1\10\30\0\2\127\52\0"+
    "\2\10\3\0\2\10\5\0\1\127\1\130\3\10\1\0"+
    "\11\10\1\0\5\10\12\0\1\10\14\0\2\10\3\0"+
    "\2\10\5\0\1\131\1\132\3\10\1\0\11\10\1\0"+
    "\5\10\12\0\1\10\14\0\2\10\3\0\2\10\6\0"+
    "\1\10\1\133\2\10\1\0\11\10\1\0\5\10\12\0"+
    "\1\10\14\0\2\10\3\0\2\10\6\0\3\10\1\134"+
    "\1\0\11\10\1\0\5\10\12\0\1\10\14\0\2\10"+
    "\3\0\2\10\6\0\2\10\1\135\1\10\1\0\11\10"+
    "\1\0\5\10\12\0\1\10\14\0\2\10\3\0\2\10"+
    "\6\0\4\10\1\0\6\10\1\136\2\10\1\0\5\10"+
    "\12\0\1\10\14\0\2\10\3\0\2\10\6\0\4\10"+
    "\1\137\1\140\10\10\1\0\5\10\12\0\1\10\14\0"+
    "\2\10\3\0\2\10\6\0\4\10\1\0\11\10\1\0"+
    "\3\10\1\141\1\10\12\0\1\10\14\0\2\10\3\0"+
    "\2\10\5\0\1\142\1\143\3\10\1\0\11\10\1\0"+
    "\5\10\12\0\1\10\13\0\14\121\1\144\57\121\1\117"+
    "\7\121\1\144\53\121\4\145\1\146\3\145\1\147\1\150"+
    "\2\151\1\152\53\145\1\0\2\10\3\0\2\10\6\0"+
    "\4\10\1\153\1\154\10\10\1\0\5\10\12\0\1\10"+
    "\33\0\1\155\50\0\2\10\3\0\2\10\6\0\2\10"+
    "\1\156\1\10\1\0\11\10\1\0\5\10\12\0\1\10"+
    "\52\0\1\157\31\0\2\10\3\0\2\10\6\0\4\10"+
    "\1\0\11\10\1\0\2\10\1\160\2\10\12\0\1\10"+
    "\34\0\1\161\47\0\2\10\3\0\2\10\6\0\3\10"+
    "\1\162\1\0\11\10\1\0\5\10\12\0\1\10\14\0"+
    "\2\10\3\0\2\10\6\0\4\10\1\0\10\10\1\163"+
    "\1\0\5\10\12\0\1\10\14\0\2\10\3\0\2\10"+
    "\6\0\3\10\1\164\1\0\11\10\1\0\5\10\12\0"+
    "\1\10\14\0\2\10\3\0\2\10\6\0\4\10\1\0"+
    "\10\10\1\165\1\0\5\10\12\0\1\10\14\0\2\10"+
    "\3\0\2\10\6\0\4\10\1\0\11\10\1\0\2\10"+
    "\1\166\2\10\12\0\1\10\33\0\1\167\50\0\2\10"+
    "\3\0\2\10\6\0\2\10\1\170\1\10\1\0\11\10"+
    "\1\0\5\10\12\0\1\10\14\0\2\10\3\0\2\10"+
    "\6\0\2\10\1\171\1\10\1\0\11\10\1\0\5\10"+
    "\12\0\1\10\44\0\1\172\37\0\2\10\3\0\2\10"+
    "\6\0\4\10\1\0\6\10\1\173\2\10\1\0\5\10"+
    "\12\0\1\10\13\0\10\151\1\174\3\151\1\175\53\151"+
    "\4\64\1\117\3\64\1\176\1\120\2\121\1\122\53\64"+
    "\10\121\1\177\3\121\1\144\57\121\1\117\3\121\1\177"+
    "\3\121\1\144\53\121\4\64\1\117\3\64\1\200\1\120"+
    "\2\121\1\122\53\64\20\0\1\201\50\0\2\10\3\0"+
    "\2\10\6\0\2\10\1\202\1\10\1\0\11\10\1\0"+
    "\5\10\12\0\1\10\51\0\1\203\32\0\2\10\3\0"+
    "\2\10\6\0\4\10\1\0\11\10\1\0\1\10\1\204"+
    "\3\10\12\0\1\10\33\0\1\205\50\0\2\10\3\0"+
    "\2\10\6\0\2\10\1\206\1\10\1\0\11\10\1\0"+
    "\5\10\12\0\1\10\14\0\2\10\3\0\2\10\6\0"+
    "\4\10\1\0\11\10\1\0\3\10\1\207\1\10\12\0"+
    "\1\10\14\0\2\10\3\0\2\10\6\0\4\10\1\0"+
    "\11\10\1\210\1\211\4\10\12\0\1\10\14\0\2\10"+
    "\3\0\2\10\5\0\1\212\1\213\3\10\1\0\11\10"+
    "\1\0\5\10\12\0\1\10\52\0\1\214\31\0\2\10"+
    "\3\0\2\10\6\0\4\10\1\0\11\10\1\0\2\10"+
    "\1\215\2\10\12\0\1\10\13\0\10\121\1\216\3\121"+
    "\1\144\53\121\4\61\1\62\3\61\1\145\1\63\2\0"+
    "\54\61\10\0\1\151\104\0\1\217\43\0\2\10\3\0"+
    "\2\10\6\0\4\10\1\0\2\10\1\220\6\10\1\0"+
    "\5\10\12\0\1\10\14\0\2\10\3\0\2\10\6\0"+
    "\3\10\1\221\1\0\11\10\1\0\5\10\12\0\1\10"+
    "\44\0\1\222\37\0\2\10\3\0\2\10\6\0\4\10"+
    "\1\0\6\10\1\223\2\10\1\0\5\10\12\0\1\10"+
    "\14\0\2\10\3\0\2\10\6\0\4\10\1\0\11\10"+
    "\1\0\2\10\1\224\2\10\12\0\1\10\53\0\1\225"+
    "\30\0\2\10\3\0\2\10\6\0\4\10\1\0\11\10"+
    "\1\0\3\10\1\226\1\10\12\0\1\10\33\0\1\227"+
    "\50\0\2\10\3\0\2\10\6\0\2\10\1\230\1\10"+
    "\1\0\11\10\1\0\5\10\12\0\1\10\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5152];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\2\1\1\11\15\1\1\11"+
    "\1\1\4\11\3\1\2\11\1\1\11\11\2\0\1\11"+
    "\2\0\1\11\1\1\1\0\2\11\5\1\1\0\10\1"+
    "\1\11\2\1\5\11\4\1\2\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\0\5\1\1\0\2\1\1\0\1\1"+
    "\2\0\3\1\3\0\1\1\1\11\1\1\1\0\1\1"+
    "\1\0\5\1\1\11\2\1\1\0\1\1\1\11\3\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\11\2\1\1\11"+
    "\1\1\1\0\1\1\1\11\2\1\1\11\2\1\1\0"+
    "\2\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { String TipoError = "Lexico ";
                            String Descripcion = "El Caracter:" + yytext() + " no pertenece al lenguaje";
                            String Fila = " Fila: " + yyline;
                            String Columna = " Columna: " + yycolumn;
                            System.out.println("#ERROR"  + TipoError + Descripcion + Fila + Columna );
                            TError ERRORES = new TError(yytext(),yyline,yycolumn,TipoError, Descripcion);
                            TABLA_DE_ERRORES_SINTACTICOS.add(ERRORES);
                            System.out.println(" al agran puta");
            }
          case 51: break;
          case 2: 
            { System.out.println("--->"+yytext()+" - entero");
                            return new Symbol(Simbolos.entero, yycolumn, yyline, yytext());
            }
          case 52: break;
          case 3: 
            { /* Se ignora */
            }
          case 53: break;
          case 4: 
            { System.out.println("--->"+yytext()+" - id");
                            return new Symbol(Simbolos.id, yycolumn, yyline, yytext());
            }
          case 54: break;
          case 5: 
            { System.out.println("--->"+yytext()+" - por");
                            return new Symbol(Simbolos.por, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 6: 
            { System.out.println("--->"+yytext()+" - llave abrir");
                            return new Symbol(Simbolos.parentesisabrir, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 7: 
            { System.out.println("--->"+yytext()+" - igual");
                            return new Symbol(Simbolos.igual, yycolumn, yyline, yytext());
            }
          case 57: break;
          case 8: 
            { System.out.println("--->"+yytext()+" - mas");
                            return new Symbol(Simbolos.mas, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 9: 
            { System.out.println("--->"+yytext()+" - menos");
                            return new Symbol(Simbolos.menos, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 10: 
            { System.out.println("--->"+yytext()+" - dividido");
                            return new Symbol(Simbolos.div, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 11: 
            { System.out.println("--->"+yytext()+" - potencia");
                            return new Symbol(Simbolos.potencia, yycolumn, yyline, yytext());
            }
          case 61: break;
          case 12: 
            { System.out.println("--->"+yytext()+" - MayorQue");
                            return new Symbol(Simbolos.MayorQue, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 13: 
            { System.out.println("--->"+yytext()+" - MenorQue");
                            return new Symbol(Simbolos.MenorQue, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 14: 
            { System.out.println("--->"+yytext()+" - AND");
                            return new Symbol(Simbolos.AND, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 15: 
            { System.out.println("--->"+yytext()+" - OR");
                            return new Symbol(Simbolos.OR, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 16: 
            { System.out.println("--->"+yytext()+" - NOT");
                            return new Symbol(Simbolos.NOT, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 17: 
            { System.out.println("--->"+yytext()+" - PREGUNTAC");
                            return new Symbol(Simbolos.PREGUNTAC, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 18: 
            { System.out.println("--->"+yytext()+" - DOSP");
                            return new Symbol(Simbolos.DOSP, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 19: 
            { System.out.println("--->"+yytext()+" - punto y coma v*****v*****v*****v*****v*****\n");
                            return new Symbol(Simbolos.puntoycoma, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 20: 
            { System.out.println("--->"+yytext()+" - llave abrir");
                            return new Symbol(Simbolos.llaveabrir, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 21: 
            { System.out.println("--->"+yytext()+" - llave cerrar");
                            return new Symbol(Simbolos.llavecerrar, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 22: 
            { System.out.println("--->"+yytext()+" - llave cerrar");
                            return new Symbol(Simbolos.parentesiscerrar, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 23: 
            { System.out.println("--->"+yytext()+" - Corchete abrir");
                            return new Symbol(Simbolos.corcheteabrir, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 24: 
            { System.out.println("--->"+yytext()+" - Corchete cerrar");
                            return new Symbol(Simbolos.corchetecerrar, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 25: 
            { System.out.println("--->"+yytext()+" - coma");
                            return new Symbol(Simbolos.coma, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 26: 
            { System.out.println("--->"+yytext()+" - CADENA");
                            return new Symbol(Simbolos.cadena, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 27: 
            { System.out.println("--->Comentario 1 línea");
            }
          case 77: break;
          case 28: 
            { System.out.println("--->"+yytext()+" - IF");
                            return new Symbol(Simbolos.IF, yycolumn, yyline, yytext());
            }
          case 78: break;
          case 29: 
            { System.out.println("--->"+yytext()+" - IN");
                            return new Symbol(Simbolos.IN, yycolumn, yyline, yytext());
            }
          case 79: break;
          case 30: 
            { System.out.println("--->"+yytext()+" - DO");
                            return new Symbol(Simbolos.DO, yycolumn, yyline, yytext());
            }
          case 80: break;
          case 31: 
            { System.out.println("--->"+yytext()+" - FuncionC");
                            return new Symbol(Simbolos.FuncionC, yycolumn, yyline, yytext());
            }
          case 81: break;
          case 32: 
            { System.out.println("--->"+yytext()+" - Igualdad");
                            return new Symbol(Simbolos.igualdad, yycolumn, yyline, yytext());
            }
          case 82: break;
          case 33: 
            { System.out.println("--->"+yytext()+" - modulo");
                            return new Symbol(Simbolos.modulo, yycolumn, yyline, yytext());
            }
          case 83: break;
          case 34: 
            { System.out.println("--->"+yytext()+" - MayorIgualQue");
                            return new Symbol(Simbolos.MayorIgualQue, yycolumn, yyline, yytext());
            }
          case 84: break;
          case 35: 
            { System.out.println("--->"+yytext()+" - MenorIgualQue");
                            return new Symbol(Simbolos.MenorIgualQue, yycolumn, yyline, yytext());
            }
          case 85: break;
          case 36: 
            { System.out.println("--->"+yytext()+" - NoIgualdad");
                            return new Symbol(Simbolos.Noigualdad, yycolumn, yyline, yytext());
            }
          case 86: break;
          case 37: 
            { System.out.println("--->"+yytext()+" - decimal");
                            return new Symbol(Simbolos.decimal, yycolumn, yyline, yytext());
            }
          case 87: break;
          case 38: 
            { System.out.println("--->"+yytext()+" - FOR");
                            return new Symbol(Simbolos.FOR, yycolumn, yyline, yytext());
            }
          case 88: break;
          case 39: 
            { System.out.println("--->Comentario multilínea");
            }
          case 89: break;
          case 40: 
            { System.out.println("--->"+yytext()+" - ELSE");
                            return new Symbol(Simbolos.ELSE, yycolumn, yyline, yytext());
            }
          case 90: break;
          case 41: 
            { System.out.println("--->"+yytext()+" - NULO");
                            return new Symbol(Simbolos.nulo, yycolumn, yyline, yytext());
            }
          case 91: break;
          case 42: 
            { System.out.println("--->"+yytext()+" - CASE");
                            return new Symbol(Simbolos.CASE, yycolumn, yyline, yytext());
            }
          case 92: break;
          case 43: 
            { System.out.println("--->"+yytext()+" - true");
                            return new Symbol(Simbolos.ttrue, yycolumn, yyline, yytext());
            }
          case 93: break;
          case 44: 
            { System.out.println("--->"+yytext()+" - false");
                            return new Symbol(Simbolos.tfalse, yycolumn, yyline, yytext());
            }
          case 94: break;
          case 45: 
            { System.out.println("--->"+yytext()+" - WHILE");
                            return new Symbol(Simbolos.WHILE, yycolumn, yyline, yytext());
            }
          case 95: break;
          case 46: 
            { System.out.println("--->"+yytext()+" - BREAK");
                            return new Symbol(Simbolos.BREAK, yycolumn, yyline, yytext());
            }
          case 96: break;
          case 47: 
            { System.out.println("--->"+yytext()+" - Imprimir");
                            return new Symbol(Simbolos.imprimir, yycolumn, yyline, yytext());
            }
          case 97: break;
          case 48: 
            { System.out.println("--->"+yytext()+" - SWITCH");
                            return new Symbol(Simbolos.SWITCH, yycolumn, yyline, yytext());
            }
          case 98: break;
          case 49: 
            { System.out.println("--->"+yytext()+" - DEF");
                            return new Symbol(Simbolos.DEF, yycolumn, yyline, yytext());
            }
          case 99: break;
          case 50: 
            { System.out.println("--->"+yytext()+" - CONTINUE");
                            return new Symbol(Simbolos.CONTINUE, yycolumn, yyline, yytext());
            }
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
