
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int FuncionC = 27;
  public static final int imprimir = 46;
  public static final int CASE = 57;
  public static final int CONTINUE = 55;
  public static final int corcheteabrir = 6;
  public static final int mode = 45;
  public static final int nulo = 33;
  public static final int coma = 29;
  public static final int igual = 9;
  public static final int MayorIgualQue = 21;
  public static final int mean = 43;
  public static final int FOR = 52;
  public static final int stringlength = 36;
  public static final int NOT = 24;
  public static final int AND = 22;
  public static final int touppercase = 39;
  public static final int IN = 53;
  public static final int parentesisabrir = 4;
  public static final int OR = 23;
  public static final int igualdad = 16;
  public static final int length = 35;
  public static final int puntoycoma = 8;
  public static final int PREGUNTAC = 25;
  public static final int ttrue = 31;
  public static final int IF = 48;
  public static final int tolowercase = 38;
  public static final int LISTA = 59;
  public static final int menos = 11;
  public static final int trunk = 40;
  public static final int llaveabrir = 3;
  public static final int parentesiscerrar = 5;
  public static final int EOF = 0;
  public static final int remove = 37;
  public static final int mas = 10;
  public static final int MayorQue = 19;
  public static final int error = 1;
  public static final int MenorIgualQue = 20;
  public static final int entero = 30;
  public static final int llavecerrar = 2;
  public static final int BREAK = 54;
  public static final int por = 12;
  public static final int SWITCH = 56;
  public static final int tfalse = 32;
  public static final int potencia = 14;
  public static final int id = 28;
  public static final int median = 44;
  public static final int ELSE = 49;
  public static final int typeof = 34;
  public static final int WHILE = 50;
  public static final int corchetecerrar = 7;
  public static final int MenorQue = 18;
  public static final int DOSP = 26;
  public static final int Noigualdad = 17;
  public static final int DEF = 58;
  public static final int round = 41;
  public static final int div = 13;
  public static final int decimal = 42;
  public static final int modulo = 15;
  public static final int DO = 51;
  public static final int cadena = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llavecerrar",
  "llaveabrir",
  "parentesisabrir",
  "parentesiscerrar",
  "corcheteabrir",
  "corchetecerrar",
  "puntoycoma",
  "igual",
  "mas",
  "menos",
  "por",
  "div",
  "potencia",
  "modulo",
  "igualdad",
  "Noigualdad",
  "MenorQue",
  "MayorQue",
  "MenorIgualQue",
  "MayorIgualQue",
  "AND",
  "OR",
  "NOT",
  "PREGUNTAC",
  "DOSP",
  "FuncionC",
  "id",
  "coma",
  "entero",
  "ttrue",
  "tfalse",
  "nulo",
  "typeof",
  "length",
  "stringlength",
  "remove",
  "tolowercase",
  "touppercase",
  "trunk",
  "round",
  "decimal",
  "mean",
  "median",
  "mode",
  "imprimir",
  "cadena",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "BREAK",
  "CONTINUE",
  "SWITCH",
  "CASE",
  "DEF",
  "LISTA"
  };
}

